# Generated by Django 4.0.4 on 2023-05-27 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process_manager', '0007_task_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique name for the Model', max_length=140)),
                ('description', models.TextField(blank=True, help_text='Description of the form', null=True)),
                ('couch_id', models.CharField(blank=True, help_text='Related Couchdb id', max_length=140, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique identifier for the field', max_length=140)),
                ('label', models.CharField(help_text='Field Label', max_length=140)),
                ('field_type', models.CharField(choices=[('Data', 'Data'), ('Check', 'Check'), ('Integer', 'Integer'), ('Float', 'Float'), ('Select', 'Select'), ('Small Text', 'Small Text'), ('Text', 'Text'), ('Page Break', 'Page Break')], help_text='Type of field', max_length=140)),
                ('help_text', models.CharField(blank=True, help_text='Text to be displayed as help', max_length=255, null=True)),
                ('required', models.BooleanField(help_text='Is the field mandatory')),
                ('options', models.TextField(blank=True, help_text='For Select, enter list of Options, each on a new line.', null=True)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Order in form')),
                ('page', models.PositiveSmallIntegerField(default=1, help_text='Page to appear in form')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.formtype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='form_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process_manager.formtype'),
        ),
    ]
